version: '2'
services:
    ecommerceapplication-app:
        image: ecommerceapplication
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://ecommerceapplication-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=EcommerceApplication
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ecommerceapplication-mongodb:
        extends:
            file: mongodb.yml
            service: ecommerceapplication-mongodb
